language: rust
before_install:
    - rustup component add rustfmt
script:
    - cargo fmt --all -- --check
    - cargo build --verbose
    - cargo test --verbose
rust:
    - stable
    - beta

# Lets skip nightly while rustfmt is different for it
#     - nightly 
# jobs:
#     allow_failures:
#         - rust: nightly
#     fast_finish: true
cache: cargo
