[package]
name = "mrt"
version = "0.1.0"
authors = ["Jonas Natten <jonas@natten.it>"]
edition = "2018"

[dependencies]
clap = "2" # Command line argument parser

# Json libraries
serde = "1.0.98"
serde_derive = "1.0.98"
serde_json = "1.0.40"