[package]
name = "mrt"
version = "0.1.0"
authors = ["Jonas Natten <jonas@natten.it>"]
edition = "2018"

[dependencies]
clap = "2" # Command line argument parser

# Json libraries
serde = { version = "1.0.98", features = ["derive"]}
serde_derive = "1.0.98"
serde_json = "1.0.40"

dirs = "2.0.2"
